# SPDX-License-Identifier: BSD-3-Clause
"""
Usermode build configuration.
"""

from SCons.Environment import Environment
from SCons.Script import Export

from scripts.scons.arch import GetArchConfig


Import("TargetEnvironment")
TargetEnvironment: Environment

# Usermode Environment Setup

UsermodeEnv = TargetEnvironment.Clone()
Architecture = TargetEnvironment["BuildArch"]

ArchitectureConfig = GetArchConfig(Architecture)
UsermodeEnv.Append(
    ASFLAGS=ArchitectureConfig.get("AssemblyFlags", []),
    CCFLAGS=ArchitectureConfig.get("CompilerFlags", []),
    LINKFLAGS=ArchitectureConfig.get("LinkerFlags", []),
)

UsermodeEnv.Append(
    CPPDEFINES={
        "_POSIX_C_SOURCE=200809L": None, 
        "VALECIUM_USR": None,
    },
)

UsermodeEnv.Replace(
    SHLIBPREFIX="lib",
    SHLIBSUFFIX=".so",
)

Export("UsermodeEnv")

# Build Sub-projects

SConscript("libmath/SConscript", variant_dir="libmath_build", duplicate=0)
SConscript("sh/SConscript", variant_dir="sh_build", duplicate=0)
SConscript("selftest/SConscript", variant_dir="selftest_build", duplicate=0)

# Export Build Products

Import("LibmathModule")
Import("ShModule")
Import("SelftestModule")

UserLibraries = [LibmathModule]
UserApplications = [
    ShModule,
    SelftestModule,
]

Export("UserLibraries")
Export("UserApplications")
