# SPDX-License-Identifier: BSD-3-Clause
"""
selftest - Freestanding user-mode syscall test application build configuration.
"""

from SCons.Script import Dir, Export

from scripts.scons.utility import GlobSources

Import("UsermodeEnv")

Env = UsermodeEnv.Clone()

SourcePath = Dir("#usr/selftest").abspath

Env.Append(
    CPPPATH=[SourcePath],
    CCFLAGS=[
        "-ffreestanding",
        "-fno-builtin",
        "-fno-pie",
        "-fno-stack-protector",
    ],
    LINKFLAGS=[
        "-nostdlib",
        "-nostartfiles",
        "-nodefaultlibs",
        "-static",
        "-Wl,-e,_start",
        "-no-pie",
    ],
)

Sources = GlobSources(SourcePath)
Objects = Env.Object(Sources)

SelftestExecutable = Env.Program("selftest", Objects)

SelftestModule = SelftestExecutable
Export("SelftestModule")
