# SPDX-License-Identifier: BSD-3-Clause
"""
libmath - Math library build configuration.
"""

from SCons.Script import Dir, Export

from scripts.scons.utility import GlobSources

Import("UsermodeEnv")

Env = UsermodeEnv.Clone()

SourcePath = Dir("#usr/libmath").abspath

Env.Append(
    CCFLAGS=["-fPIC"],
    CFLAGS=["-fPIC"],
    LINKFLAGS=[
        "-shared",
        "-Wl,-soname,libmath.so",
    ],
    CPATH=[SourcePath],
    CPPPATH=[SourcePath],
    ASFLAGS=["-I", SourcePath + "/", "-f", "elf"],
)

Sources = GlobSources(SourcePath)
Objects = Env.SharedObject(Sources)

LibmathLibrary = Env.SharedLibrary("math", Objects)

LibmathModule = LibmathLibrary
Export("LibmathModule")
