# SPDX-License-Identifier: BSD-3-Clause
"""
Bootloader build configuration.
"""

import os
# import sys
# import subprocess

from SCons.Environment import Environment
from SCons.Script import Dir, Export, SConscript

from scripts.scons.arch import GetArchConfig
from scripts.scons.bootloader import (
    ConfigureBootloaderEnvironment,
    GetBootloaderBuildConfig,
)


Import("TargetEnvironment")
TargetEnvironment: Environment

# =============================================================================
# Environment Setup
# =============================================================================

MainEnvironment = TargetEnvironment.Clone()

BootType = TargetEnvironment["BootType"]
SourcePath = Dir("#boot").abspath
Architecture = TargetEnvironment["BuildArch"]
ArchitecturePath = os.path.join(SourcePath, BootType, Architecture)
ProjectVersion = TargetEnvironment["ProjVersion"]

ArchitectureConfig = GetArchConfig(Architecture)
BuildConfig = TargetEnvironment["BuildConfig"]
BootloaderBuildConfig = GetBootloaderBuildConfig(
    BootType, Architecture, ProjectVersion, BuildConfig
)

ConfigureBootloaderEnvironment(
    MainEnvironment,
    SourcePath,
    ArchitecturePath,
    ArchitectureConfig,
    BootloaderBuildConfig,
)

MainEnvironment.Append(
    LINKFLAGS=[
        "-Wl,-N",
        "-static-libgcc",
    ],
    OBJPREFIX="main_",
)

# =============================================================================
# Source Files
# =============================================================================

Sources = []
CoreFsSources = []
CoreSources = []
CoreFsSharedSources = []
SConscript(
    "common/SConscript",
    exports=[
        "Sources",
        "CoreFsSources",
        "CoreSources",
        "CoreFsSharedSources",
        "SourcePath",
    ],
)

# =============================================================================
# Bootloader Components
# =============================================================================

TargetEnvironment["BootloaderComponents"]["BootType"] = BootType
TargetEnvironment["BootloaderComponents"]["Architecture"] = Architecture

if BootType == "bios":
    SConscript(
        "bios/SConscript",
        exports=[
            "TargetEnvironment",
            "SourcePath",
            "ArchitecturePath",
            "ArchitectureConfig",
            "BootloaderBuildConfig",
            "Sources",
            "CoreFsSources",
            "CoreSources",
            "CoreFsSharedSources",
            "Architecture",
        ],
    )
elif BootType == "efi":
    SConscript(
        "efi/SConscript",
        exports=[
            "TargetEnvironment",
            "SourcePath",
            "ArchitecturePath",
            "ArchitectureConfig",
            "BootloaderBuildConfig",
            "Sources",
            "CoreSourcesCoreFsSharedSources",
            "Architecture",
        ],
    )
else:
    raise RuntimeError(f"Unsupported boot type: {BootType}")

# =============================================================================
# Build Target
# =============================================================================

Objects = MainEnvironment.SharedObject(Sources)
Bootloader = MainEnvironment.SharedLibrary(BootloaderBuildConfig["OutputName"], Objects)

TargetEnvironment["BootloaderComponents"]["Main"] = Bootloader

TargetEnvironment["BootloaderComponents"]["Config"] = TargetEnvironment.File(
    os.path.join("common", "conf", "TheBootloader.conf.eg")
).srcnode()

Export("Bootloader")
