#!/opt/local/bin/python3
"""Generate the Valecium boot logo C header from the source PNG.

Usage: mklogo.py <logo_gen.h>

Output: 640x640, 3 colours (white, blue, black), 4bpp format.
"""

import sys
import os
from pathlib import Path
from PIL import Image

SCRIPT_DIR = Path(__file__).absolute().parent
REPO_ROOT = Path(os.path.normpath(SCRIPT_DIR / ".." / ".." / ".."))
SRC_PNG = REPO_ROOT / "Documentation" / "assets" / "ValeciumOS.png"

if len(sys.argv) < 2:
    print("Usage: mklogo.py <logo_gen.h>")
    sys.exit(1)

out_h = sys.argv[1]

# Target colours (R, G, B)
WHITE_COLOUR = (252, 252, 252)
BLUE_COLOUR = (228, 250, 254)
BLACK_COLOUR = (0, 0, 0)
COLOURS = [WHITE_COLOUR, BLUE_COLOUR, BLACK_COLOUR]

LOGO_W = 640
LOGO_H = 640


def NearestColour(r, g, b):
    best = 0
    best_dist = 3 * 256 * 256
    for i, (cr, cg, cb) in enumerate(COLOURS):
        d = (r - cr) * (r - cr) + (g - cg) * (g - cg) + (b - cb) * (b - cb)
        if d < best_dist:
            best_dist = d
            best = i
    return best


def QuantizeTo3Colours(img):
    out = Image.new("P", img.size)
    pixels = img.load()
    o_pixels = out.load()
    w, h = img.size
    for y in range(h):
        for x in range(w):
            r, g, b, a = pixels[x, y][:4]
            if a < 128:
                o_pixels[x, y] = 2  # transparent -> black
            else:
                o_pixels[x, y] = NearestColour(r, g, b)
    return out


def Pack4Bpp(pixels, w, h):
    data = bytearray((w * h + 1) // 2)
    for i, val in enumerate(pixels):
        if val & ~0x0F:
            raise ValueError(f"Pixel value {val} out of range for 4bpp")
        byte_idx = i >> 1
        if i & 1:
            data[byte_idx] |= val  # low nibble
        else:
            data[byte_idx] |= val << 4  # high nibble
    return data


def FormatCArray(data, width=16):
    lines = []
    for i in range(0, len(data), width):
        chunk = data[i : i + width]
        hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"   {hex_str}, ")
    return "\n".join(lines)


def main():
    src = Image.open(SRC_PNG).convert("RGBA")
    sw, sh = src.size

    size = min(sw, sh)
    left = (sw - size) // 2
    top = (sh - size) // 2
    square = src.crop((left, top, left + size, top + size))

    quant = QuantizeTo3Colours(square)
    final = quant.resize((LOGO_W, LOGO_H), Image.NEAREST)

    pixels = final.getdata()
    data = Pack4Bpp(pixels, LOGO_W, LOGO_H)

    data_str = FormatCArray(data)
    pal_str = ", ".join(f"0x{r:02X}, 0x{g:02X}, 0x{b:02X}" for r, g, b in COLOURS)

    header = f"""// Auto-generated by {Path(__file__).name} from {SRC_PNG.relative_to(REPO_ROOT)}
// 3 colours, {LOGO_W}x{LOGO_H}, 4bpp
#pragma once

#include <stdint.h>

#define VALECIUM_LOGO_W {LOGO_W}
#define VALECIUM_LOGO_H {LOGO_H}
#define VALECIUM_LOGO_PALETTE_SIZE {len(COLOURS)}

static const uint8_t s_ValeciumLogo_PaletteRGB[] = {{
   {pal_str}
}};

static const uint8_t s_ValeciumLogo_Data4bpp[] = {{
{data_str}
}};
"""

    with open(out_h, "w") as f:
        f.write(header)


if __name__ == "__main__":
    main()
