# SPDX-License-Identifier: BSD-3-Clause
"""
Kernel build configuration.
"""

import os
import sys
import subprocess

from SCons.Environment import Environment
from SCons.Script import Dir, Export, SConscript

from scripts.scons.arch import GetArchConfig
from scripts.scons.kernel import (
    ConfigureKernelEnvironment,
    GetKernelBuildConfig,
)


Import("TargetEnvironment")
TargetEnvironment: Environment

# =============================================================================
# Environment Setup
# =============================================================================

KernelEnv = TargetEnvironment.Clone()

KernelType = TargetEnvironment["KernelType"]
SourcePath = Dir("#kernel").abspath
Architecture = TargetEnvironment["BuildArch"]
ArchitecturePath = os.path.join(SourcePath, "arch", Architecture)
ProjectVersion = TargetEnvironment["ProjVersion"]
LinkerScript = os.path.join(ArchitecturePath, "linker.ld")

ArchitectureConfig = GetArchConfig(Architecture)
BuildConfig = TargetEnvironment["BuildConfig"]
KernelBuildConfig = GetKernelBuildConfig(
    KernelType, Architecture, ProjectVersion, BuildConfig
)

ConfigureKernelEnvironment(
    KernelEnv,
    SourcePath,
    ArchitecturePath,
    ArchitectureConfig,
    KernelBuildConfig,
    LinkerScript,
)

# =============================================================================
# Generated Source Files
# =============================================================================

MkisrsPath = os.path.join(ArchitecturePath, "cpu", "mkisrs.py")
if os.path.exists(MkisrsPath):
    IsrsGenC = os.path.join(ArchitecturePath, "cpu", "isrs_gen.c")
    IsrsGenInc = os.path.join(ArchitecturePath, "cpu", "isrs_gen.inc")

    if not os.path.exists(IsrsGenC) or not os.path.exists(IsrsGenInc):
        subprocess.run([sys.executable, MkisrsPath, IsrsGenC, IsrsGenInc], check=True)

# =============================================================================
# Source Files
# =============================================================================

Sources = []

SConscript("arch/SConscript", exports="Sources")
SConscript("cpu/SConscript", exports="Sources")
SConscript("crypto/SConscript", exports="Sources")
SConscript("drivers/SConscript", exports="Sources")
SConscript("fs/SConscript", exports="Sources")
SConscript("hal/SConscript", exports="Sources")
SConscript("init/SConscript", exports="Sources")
SConscript("mem/SConscript", exports="Sources")
SConscript("signal/SConscript", exports="Sources")
SConscript("std/SConscript", exports="Sources")
SConscript("sys/SConscript", exports="Sources")
SConscript("syscall/SConscript", exports="Sources")

# =============================================================================
# Build Target
# =============================================================================

Objects = KernelEnv.Object(Sources)
Kernel = KernelEnv.Program(KernelBuildConfig["OutputName"], Objects)

TargetEnvironment["KernelComponents"]["Main"] = Kernel

Export("Kernel")
