# SPDX-License-Identifier: BSD-3-Clause
"""
sh - Shell application build configuration.
"""

from SCons.Script import Dir, Export

from scripts.scons.utility import GlobSources

Import("UsermodeEnv")

Env = UsermodeEnv.Clone()

SourcePath = Dir("#usr/sh").abspath

Env.Append(
    CPPPATH=[SourcePath],
)

Sources = GlobSources(SourcePath)
Objects = Env.Object(Sources)

ShExecutable = Env.Program("sh", Objects)

ShModule = ShExecutable
Export("ShModule")
