.PHONY: all

TEX_FILES=TheValkyriezOperatingSystem.tex
OUTPUT_DIR=../build/docs

all: TheValkyrieOperatingSystem.tex

TheValkyrieOperatingSystem.tex:
	@mkdir -p $(OUTPUT_DIR)
	@pdflatex --output-directory=$(OUTPUT_DIR) TheValkyrieOperatingSystem.tex
